name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
    
    - name: Install dependencies
      run: |
        echo "Installing dependencies with uv..."
        uv pip install -e .[dev]
        echo "Dependencies installed successfully"
    
    - name: Lint with flake8
      run: |
        echo "Running flake8 syntax check..."
        # stop the build if there are Python syntax errors or undefined names
        uv run flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
        echo "Running flake8 full check..."
        uv run flake8 src --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics
    
    - name: Format check with black
      run: |
        echo "Checking code formatting with black..."
        uv run black --check src
    
    - name: Type check with mypy
      run: |
        echo "Running type check with mypy..."
        uv run mypy src --ignore-missing-imports
    
    - name: Test with pytest
      run: |
        echo "Running tests with pytest..."
        uv run pytest tests/ -v
