name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        version: "latest"
    
    - name: Install dependencies
      run: |
        uv sync --dev
        # Fallback to pip if uv sync fails
        if [ $? -ne 0 ]; then
          python -m pip install --upgrade pip
          pip install -e .[dev]
        fi
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        uv run flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics || flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        uv run flake8 src --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics || flake8 src --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics
    
    - name: Format check with black
      run: |
        uv run black --check src || black --check src
    
    - name: Type check with mypy
      run: |
        uv run mypy src --ignore-missing-imports || mypy src --ignore-missing-imports
    
    - name: Test with pytest
      run: |
        uv run pytest tests/ -v || pytest tests/ -v
